version: '3.7'

services:
    dev-php:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: dev-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - travellist


    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
        - "8080:80"
        volumes:
        - ./html:/var/www
        # - ./docker-compose/nginx:/etc/nginx/conf.d
        - ./nginx:/etc/nginx/conf.d
        networks:
        - travellist

networks:
  travellist:
    driver: bridge